global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'storagehub-bsp'
    static_configs:
      - targets: ['sh-bsp:9615']
        labels:
          role: 'bsp'

  - job_name: 'storagehub-msp-1'
    static_configs:
      - targets: ['sh-msp-1:9615']
        labels:
          role: 'msp'
          instance_num: '1'

  - job_name: 'storagehub-msp-2'
    static_configs:
      - targets: ['sh-msp-2:9615']
        labels:
          role: 'msp'
          instance_num: '2'

  - job_name: 'storagehub-user'
    static_configs:
      - targets: ['sh-user:9615']
        labels:
          role: 'user'

  - job_name: 'storagehub-fisherman'
    static_configs:
      - targets: ['sh-fisherman:9615']
        labels:
          role: 'fisherman'

  - job_name: 'storagehub-indexer'
    static_configs:
      - targets: ['sh-indexer:9615']
        labels:
          role: 'indexer'
